---
# Default variables (fallback for unknown OS)
# Assumes Debian-like structure
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_data_path: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_service_name: "postgresql"
