---
- name: Restart PostgreSQL
  systemd:
    name: "{{ postgresql_service_name }}"
    state: restarted

- name: Reload PostgreSQL
  systemd:
    name: "{{ postgresql_service_name }}"
    state: reloaded
